//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answer = new HashSet<Answer>();
            this.MultiOption = new HashSet<MultiOption>();
        }
    
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public string QuestionDesc { get; set; }
        public bool AnswerRequired { get; set; }
        public Nullable<byte> RatingMaxValue { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> InputId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual InputType InputType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiOption> MultiOption { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
